### ISSUE TITLE
restclient-ui-fat-3.6.jar throw an exception

### ISSUE THREAD

**Issue by firstrose** [wiztools/rest-client#53]
just click restclient-ui-fat-3.6.jar to run it and get a error message,

![firefox_2016-06-07_14-41-36](https://cloud.githubusercontent.com/assets/1551595/15848245/5dd57ba6-2cbe-11e6-854a-3c5c3ad1006c.JPG)

But 3.5 runs OK.

**Comment by subwiz** [comment]
Can you run from the command prompt and copy-paste the exception trace:

```
c:> java -jar restclient-ui-fat-3.6.jar
```

**Comment by firstrose** [comment]
emmmmmmm.....I guess you upgraded JDK after restclient v3.5......  My jre is a little outdated :jre1.7.0_51_x64 .  Is it the reason?
Thank you for your reply.

=====================================================
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/wiztools/restclient/ui/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by subwiz** [comment]
Yes, now we need JRE1.8 minimum. Please update!

https://github.com/wiztools/rest-client/wiki/Running
