### ISSUE TITLE
Cannot perform update check -- connection timed out

### ISSUE THREAD

**Issue by Kristianwhittick** [wiztools/rest-client#58]
Does the Update check use the proxy settings?
It always fails.

INFO: Cannot perform update check...
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at org.wiztools.appupdate.VersionWSUtil.getLatestVersion(VersionWSUtil.java:20)
        at org.wiztools.restclient.ui.update.AppUpdateRunner.run(AppUpdateRunner.java:65)
        at java.lang.Thread.run(Unknown Source)

**Comment by subwiz** [comment]
Short term solution:

Edit `~/.rest-client/rest-client.properties` add the property `update.check.enabled = false` to disable update check. I would encourage you to update to the latest version.

Will look into fixing this as well.
