### ISSUE TITLE
java.lang.NullPointerException while using rest-client tool

### ISSUE THREAD

**Issue by Pralima** [wiztools/rest-client#76]
Hi All,

Getting below error popup while hitting service endpoint with rest client. Truststore and Keystore settings are in place and same set up works for other colleague but error for me.

null
java.lang.NullPointerException
  at org.wiztools.restclient.bean.ReqEntityByteArrayBean.getBody(ReqEntityByteArrayBean.java:20)
  at org.wiztools.restclient.HTTPClientUtil.getEntity(HTTPClientUtil.java:92)
  at org.wiztools.restclient.HTTPClientRequestExecuter.execute(HTTPClientRequestExecuter.java:283)
  at org.wiztools.restclient.ui.RESTViewImpl$2.run(RESTViewImpl.java:322)

**Comment by subwiz** [comment]
Need information:

1. Version of RESTClient
2. JRE version
3. OS

**Comment by subwiz** [comment]
No further input received, closing.
