### ISSUE TITLE
Failure to start with systemstats error message in system.log

### ISSUE THREAD

**Issue by prestonmcgowan** [wiztools/rest-client#80]
My older rest-client UI alerted me to an update.
After I installed the update, I receive the following in the system.log when I try to start the application. 
`systemstats[85]: assertion failed: 17G65: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40`
The rest-client immediately stops.

Version Info:
- rest-client: 3.7.0
- Java: Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
- macOS High Sierra 10.13.6

**Comment by prestonmcgowan** [comment]
I upgrade java and still received the same error
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

**Comment by prestonmcgowan** [comment]
More info from /Applications/RESTClient.app/Contents/MacOS/JavaAppLauncher
`$ ./JavaAppLauncher 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/wiztools/restclient/ui/Main has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)`

**Comment by prestonmcgowan** [comment]
I updated Java to 11 an still have the same errors printed as all of the above.
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)

**Comment by prestonmcgowan** [comment]
rest-client versions tested:
- 3.6 - works
- 3.6.1 - works
- 3.6.2 - systemstats error
- 3.7.0 - systemstats error

**Comment by subwiz** [comment]
Thanks for the detailed note. I'll make it compatible with Java 8 this weekend. It should ideally solve the problem.

**Comment by subwiz** [comment]
(cross posting from #77 )

I've modified the code and dependencies to support Java 8. A build of this version is available here:

* http://download.wiztools.org/rest-client/restclient-ui-fat-3.7.1-SNAPSHOT.jar
* http://download.wiztools.org/rest-client/restclient-ui-3.7.1-SNAPSHOT.dmg

Can the audience test the builds and let me know if it works as expected? Especially in Mac I want help knowing if the `.dmg` version works with both Java 8 (with no Java 10 installed in parallel) and Java 10.

Once this sanity confirmation is given by the community, I'll publish the release.

**Comment by prestonmcgowan** [comment]
Thanks. I have tested basic functionality on my system.
<3 rest-client
