### ISSUE TITLE
Remote host closed connection during handshake

### ISSUE THREAD

**Issue by pplmx** [wiztools/rest-client#85]
```java
Error:
Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.jsse2.av.a(av.java:782)
	at com.ibm.jsse2.av.i(av.java:574)
	at com.ibm.jsse2.av.a(av.java:280)
	at com.ibm.jsse2.av.startHandshake(av.java:431)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.wiztools.restclient.HTTPClientRequestExecuter.execute(HTTPClientRequestExecuter.java:391)
	at org.wiztools.restclient.cli.CliMain.main(CliMain.java:144)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.ibm.jsse2.b.a(b.java:231)
	at com.ibm.jsse2.av.a(av.java:579)
	... 16 more

```

**Comment by subwiz** [comment]
Are you using IBM JDK?

**Comment by mystic-cg** [comment]
> Are you using IBM JDK?

No, I used Oracle JDK

**Comment by subwiz** [comment]
Seems to be server specific SSL issue.
